# -*- coding: utf-8 -*-
"""Regression_Analysis (5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwjRXyP3URtO9f5Imw2Pqbc__Du_eis7

# 📊 Marketing ROI Analysis — Simple Linear Regression

**Objective:** Determine which marketing channel (TV, Radio, or Social Media) most strongly drives Sales, quantify the relationship using Simple Linear Regression, validate the model's statistical assumptions, and translate the results into a budget recommendation.

**Dataset:** `marketing_and_sales_data_evaluate.csv` — spend (in \$) on TV, Radio, and Social Media advertising, and resulting Sales (in \$).

**Workflow:**
1. Load & clean the data
2. Exploratory Data Analysis (correlations, pairplot, heatmap, scatter plots)
3. Build an OLS regression model (Sales ~ TV)
4. Diagnostic plots (linearity, normality, homoscedasticity)
5. Formal statistical tests (Shapiro-Wilk, Durbin-Watson, Breusch-Pagan)
6. Compare ROI across all three channels
7. Final recommendation & budget allocation
"""

# ============================================
# MARKETING ROI ANALYSIS - SIMPLE LINEAR REGRESSION
# ============================================

# ---- IMPORT REQUIRED LIBRARIES ----
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.stattools import durbin_watson

# Set plot style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
print("Libraries imported successfully!")
print("=" * 60)

# ============================================
# STEP 1: LOAD AND CLEAN DATA
# ============================================
print("STEP 1: LOAD AND CLEAN DATA")
print("=" * 60)

df = pd.read_csv('marketing_and_sales_data_evaluate.csv')
print(f"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Columns: {df.columns.tolist()}")

print("\nMissing values per column:")
print(df.isnull().sum())

# Handle missing values - DROP rows with missing values
df_clean = df.dropna()
print(f"\nData Cleaning Summary:")
print(f"  Original rows: {len(df)}")
print(f"  Rows after cleaning: {len(df_clean)}")
print(f"  Rows removed: {len(df) - len(df_clean)}")
print(f"  Missing values remaining: {df_clean.isnull().sum().sum()}")

print("\nSummary Statistics (Cleaned Data):")
print(df_clean.describe().round(2))

# ============================================
# STEP 2: EXPLORATORY DATA ANALYSIS (EDA)
# ============================================
print("\n" + "=" * 60)
print("STEP 2: EXPLORATORY DATA ANALYSIS")
print("=" * 60)

# Correlation with Sales
correlations = df_clean.corr()['Sales'].drop('Sales').sort_values(ascending=False)
print("\nCorrelation with Sales:")
print(correlations)

# Identify best predictor
best_predictor = correlations.index[0]
best_correlation = correlations.iloc[0]
print(f"\nBest predictor: {best_predictor} (r = {best_correlation:.4f})")

# ---- REQUIRED: PAIRPLOT (EDA Visualization) ----
print("\nGenerating Pairplot...")
pairplot_fig = sns.pairplot(df_clean, height=2.5)
pairplot_fig.fig.suptitle('Pairplot of All Variables', y=1.02)
plt.show()

# ---- REQUIRED: CORRELATION HEATMAP ----
print("\nGenerating Correlation Heatmap...")
plt.figure(figsize=(10, 8))
sns.heatmap(df_clean.corr(), annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.5)
plt.title('Correlation Heatmap', fontsize=14)
plt.show()

# ---- REQUIRED: SCATTER PLOTS WITH REGRESSION LINE ----
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
channels = ['TV', 'Radio', 'Social_Media']
for i, col in enumerate(channels):
    sns.regplot(x=col, y='Sales', data=df_clean, ax=axes[i], ci=95, line_kws={'color': 'red'})
    axes[i].set_title(f'Sales vs {col} (r = {df_clean[col].corr(df_clean["Sales"]):.4f})')
    axes[i].set_xlabel(f'{col} Spend ($)')
    axes[i].set_ylabel('Sales ($)')
plt.tight_layout()
plt.show()

# ============================================
# STEP 3: BUILD OLS REGRESSION MODEL
# ============================================
print("\n" + "=" * 60)
print("STEP 3: BUILD OLS REGRESSION MODEL")
print("=" * 60)

# Select TV as independent variable (strongest correlation with Sales)
X = df_clean[['TV']]
X = sm.add_constant(X)
y = df_clean['Sales']

# Fit model
model = sm.OLS(y, X).fit()

# ---- REQUIRED: FULL STATSMODELS SUMMARY ----
print("\nFULL REGRESSION SUMMARY TABLE:")
print(model.summary())

# Extract key statistics
r_squared = model.rsquared
coef_intercept = model.params['const']
coef_tv = model.params['TV']
p_value_tv = model.pvalues['TV']
std_err = model.bse['TV']

print("\n" + "=" * 60)
print("KEY MODEL STATISTICS")
print("=" * 60)
print(f"R-squared: {r_squared:.4f} ({r_squared * 100:.2f}%)")
print(f"Equation: Sales = {coef_intercept:.2f} + ({coef_tv:.4f}) x TV")
print(f"TV Coefficient: ${coef_tv:.4f} per $1 spent")
print(f"Intercept: ${coef_intercept:.2f}")
print(f"P-value: {p_value_tv:.4e}")
print(f"Standard Error: +/- ${std_err:.4f}")

# ============================================
# STEP 4: DIAGNOSTIC PLOTS (REQUIRED BY RUBRIC)
# ============================================
print("\n" + "=" * 60)
print("STEP 4: DIAGNOSTIC PLOTS")
print("=" * 60)

# Create 4 diagnostic plots
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# ---- REQUIRED: RESIDUALS VS FITTED (Linearity & Homoscedasticity) ----
axes[0, 0].scatter(model.fittedvalues, model.resid, alpha=0.5, color='blue')
axes[0, 0].axhline(y=0, color='red', linestyle='--', linewidth=2)
axes[0, 0].set_xlabel('Fitted Values (Predicted Sales)', fontsize=12)
axes[0, 0].set_ylabel('Residuals', fontsize=12)
axes[0, 0].set_title('Residuals vs Fitted (Linearity Check)', fontsize=14)
axes[0, 0].grid(True, alpha=0.3)

# ---- REQUIRED: Q-Q PLOT (Normality Check) ----
stats.probplot(model.resid, dist="norm", plot=axes[0, 1])
axes[0, 1].set_title('Q-Q Plot (Normality Check)', fontsize=14)
axes[0, 1].set_xlabel('Theoretical Quantiles', fontsize=12)
axes[0, 1].set_ylabel('Sample Quantiles', fontsize=12)
axes[0, 1].grid(True, alpha=0.3)

# ---- REQUIRED: SCALE-LOCATION (Homoscedasticity Check) ----
axes[1, 0].scatter(model.fittedvalues, np.sqrt(np.abs(model.resid)), alpha=0.5, color='green')
axes[1, 0].axhline(y=0, color='red', linestyle='--', linewidth=2)
axes[1, 0].set_xlabel('Fitted Values', fontsize=12)
axes[1, 0].set_ylabel('sqrt(|Residuals|)', fontsize=12)
axes[1, 0].set_title('Scale-Location (Homoscedasticity Check)', fontsize=14)
axes[1, 0].grid(True, alpha=0.3)

# ---- HISTOGRAM OF RESIDUALS ----
axes[1, 1].hist(model.resid, bins=30, edgecolor='black', alpha=0.7, color='purple')
axes[1, 1].set_xlabel('Residuals', fontsize=12)
axes[1, 1].set_ylabel('Frequency', fontsize=12)
axes[1, 1].set_title('Histogram of Residuals', fontsize=14)
axes[1, 1].axvline(x=0, color='red', linestyle='--', linewidth=2)

plt.tight_layout()
plt.show()

print("Diagnostic plots displayed:")
print("  - Residuals vs Fitted (Linearity Check)")
print("  - Q-Q Plot (Normality Check) - REQUIRED")
print("  - Scale-Location (Homoscedasticity Check)")
print("  - Histogram of Residuals")

# ============================================
# STEP 5: STATISTICAL TESTS (REQUIRED)
# ============================================
print("\n" + "=" * 60)
print("STEP 5: STATISTICAL TESTS")
print("=" * 60)

# Shapiro-Wilk test for Normality
shapiro_stat, shapiro_p = stats.shapiro(model.resid)
print(f"\n1. Shapiro-Wilk Normality Test:")
print(f"   Test statistic: {shapiro_stat:.4f}")
print(f"   p-value: {shapiro_p:.4e}")
print("   p > 0.05: Residuals are normally distributed" if shapiro_p > 0.05
      else "   p < 0.05: Residuals deviate from normality")

# Durbin-Watson test for Autocorrelation
dw = durbin_watson(model.resid)
print(f"\n2. Durbin-Watson Test (Autocorrelation):")
print(f"   Statistic: {dw:.4f}")
print("   Statistic between 1.5-2.5: No significant autocorrelation" if 1.5 <= dw <= 2.5
      else "   Statistic outside 1.5-2.5: Possible autocorrelation")

# Breusch-Pagan test for Homoscedasticity
bp_test = het_breuschpagan(model.resid, model.model.exog)
print(f"\n3. Breusch-Pagan Test (Homoscedasticity):")
print(f"   Test statistic: {bp_test[0]:.4f}")
print(f"   p-value: {bp_test[1]:.4e}")
print("   p > 0.05: Constant variance (homoscedastic) - GOOD" if bp_test[1] > 0.05
      else "   p < 0.05: Heteroscedasticity detected")

# ============================================
# STEP 6: COMPARE ALL CHANNELS (ROI ANALYSIS)
# ============================================
print("\n" + "=" * 60)
print("STEP 6: ROI COMPARISON ACROSS ALL CHANNELS")
print("=" * 60)

results = {}
for channel in ['TV', 'Radio', 'Social_Media']:
    Xc = sm.add_constant(df_clean[[channel]])
    model_c = sm.OLS(y, Xc).fit()
    results[channel] = {
        'coefficient': model_c.params[channel],
        'intercept': model_c.params['const'],
        'r_squared': model_c.rsquared,
        'p_value': model_c.pvalues[channel],
        'std_err': model_c.bse[channel]
    }
    print(f"\n{channel}:")
    print(f"  Equation: Sales = {model_c.params['const']:.2f} + ({model_c.params[channel]:.4f}) x {channel}")
    print(f"  R-squared: {model_c.rsquared:.4f} ({model_c.rsquared * 100:.2f}%)")
    print(f"  ROI: ${model_c.params[channel]:.4f} per $1 spent")
    print(f"  P-value: {model_c.pvalues[channel]:.4e}")
    print(f"  Significant: {'Yes' if model_c.pvalues[channel] < 0.05 else 'No'}")

# ---- ROI COMPARISON BAR CHART ----
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

channels = list(results.keys())
roi_values = [results[c]['coefficient'] for c in channels]
colors = ['#2ecc71', '#3498db', '#e74c3c']

axes[0].bar(channels, roi_values, color=colors, alpha=0.7, edgecolor='black')
axes[0].set_xlabel('Marketing Channel', fontsize=12)
axes[0].set_ylabel('ROI per $1 Spent ($)', fontsize=12)
axes[0].set_title('ROI Comparison Across Channels', fontsize=14)
for i, v in enumerate(roi_values):
    axes[0].text(i, v + 0.1, f'${v:.2f}', ha='center', fontsize=11, fontweight='bold')

r2_values = [results[c]['r_squared'] * 100 for c in channels]
axes[1].bar(channels, r2_values, color=colors, alpha=0.7, edgecolor='black')
axes[1].set_xlabel('Marketing Channel', fontsize=12)
axes[1].set_ylabel('R-squared (%)', fontsize=12)
axes[1].set_title('Explanatory Power Comparison', fontsize=14)
for i, v in enumerate(r2_values):
    axes[1].text(i, v + 0.5, f'{v:.1f}%', ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

# ============================================
# STEP 7: FINAL RECOMMENDATION
# ============================================
print("\n" + "=" * 60)
print("STEP 7: FINAL RECOMMENDATION")
print("=" * 60)

best_roi = max(results, key=lambda x: results[x]['coefficient'])
best_r2 = max(results, key=lambda x: results[x]['r_squared'])

print(f"\nHIGHEST ROI: {best_roi} (${results[best_roi]['coefficient']:.2f} per $1)")
print(f"BEST EXPLANATORY POWER: {best_r2} ({results[best_r2]['r_squared'] * 100:.2f}%)")

print("\n" + "=" * 60)
print("RECOMMENDATION STRATEGY")
print("=" * 60)
print("""HYBRID APPROACH:

1. MAINTAIN TV BUDGET (Current Level)
   - Drives the bulk of sales (highest R-squared)
   - Don't cut TV spend - it's the foundation

2. INCREASE SOCIAL MEDIA BUDGET (20-30%)
   - Highest ROI per dollar spent
   - Test scalability with a moderate increase

3. OPTIMIZE RADIO (Maintain Current Level)
   - Solid ROI and good explanatory power

4. CONTINUOUS MONITORING
   - Track ROI over time
   - Watch for diminishing returns
""")

# Example budget allocation
total_budget = 10000
tv_alloc = total_budget * 0.45
social_alloc = total_budget * 0.30
radio_alloc = total_budget * 0.25

projected_return = (tv_alloc * results['TV']['coefficient'] +
                     social_alloc * results['Social_Media']['coefficient'] +
                     radio_alloc * results['Radio']['coefficient'])

print("=" * 60)
print(f"EXAMPLE BUDGET ALLOCATION (${total_budget:,} budget)")
print("=" * 60)
print(f"TV (45%): ${tv_alloc:,.2f}")
print(f"Social Media (30%): ${social_alloc:,.2f}")
print(f"Radio (25%): ${radio_alloc:,.2f}")
print(f"\nProjected Return: ${projected_return:,.2f}")

# ============================================
# FINAL SUMMARY
# ============================================
print("\n" + "=" * 60)
print("FINAL PROJECT SUMMARY")
print("=" * 60)
print(f"""
DATASET: {len(df_clean)} rows, {len(df_clean.columns)} columns
BEST PREDICTOR: TV (r = {best_correlation:.4f})
R-SQUARED: {r_squared:.4f} ({r_squared * 100:.2f}%)
EQUATION: Sales = {coef_intercept:.2f} + ({coef_tv:.4f}) x TV
TV ROI: ${coef_tv:.4f} per $1
SOCIAL MEDIA ROI: ${results['Social_Media']['coefficient']:.2f} per $1
RECOMMENDATION: Maintain TV, Increase Social Media

MODEL ASSUMPTIONS CHECKED:
  - Normality (Shapiro-Wilk):       p = {shapiro_p:.4f}
  - No Autocorrelation (Durbin-W):  DW = {dw:.4f}
  - Homoscedasticity (Breusch-Pagan): p = {bp_test[1]:.4f}
""")

print("=" * 60)
print("PROJECT COMPLETED SUCCESSFULLY!")
print("=" * 60)

"""## 📝 Interpretation & Conclusion

**Model:** `Sales = β₀ + β₁ × TV`

- **TV** is by far the strongest predictor of Sales (correlation ≈ 0.999, R² ≈ 99.9%), meaning TV spend alone explains nearly all the variation in sales in this dataset.
- The TV coefficient (~\$3.56 per \$1 spent) is highly statistically significant (p < 0.001), so we can be confident this isn't a chance relationship.
- **Assumption checks** (Residuals vs Fitted, Q-Q plot, Scale-Location, Shapiro-Wilk, Durbin-Watson, Breusch-Pagan) all support that a simple linear model is appropriate here: residuals are approximately normal, homoscedastic, and not autocorrelated.
- **Radio** has a moderate relationship with Sales (R² ≈ 75%) and a strong per-dollar ROI, while **Social Media** has the highest ROI per dollar but the lowest explanatory power — meaning it's productive at current (lower) spending levels, but we have less data confidence about how it scales.

**Business takeaway:** Maintain TV as the foundation of the marketing budget (it drives the largest share of measurable sales), while testing a moderate increase in Social Media spend to capture its high marginal ROI, and keep Radio steady. Re-run this analysis periodically as new data comes in to watch for diminishing returns at higher spend levels.

"""